- name: add cron job (ansible-pull)
  cron:
    name: ansible auto-provision
    user: ansible
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/CosmicSpawn/ansible_pull_tutorial.git >> /home/ansible/ansible.log"
